BRUTE_FORCE_THRESHOLD = 3

KALI_HOST = ''
KALI_USER = ''
KALI_PASSWORD = ''

LOCAL_LOG_PATH = 'logs/remote_journal.log'
LOGS_DIR = 'logs'

EMAIL_SENDER = ''
EMAIL_RECEIVER = ''
EMAIL_APP_PASSWORD = '' 
